<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
=======
# Generated by Django 5.0.3 on 2024-04-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
>>>>>>> 49cc1c162d40e4b298df25389748a49b7cebbf23
