# Generated by Django 5.0.3 on 2024-04-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0003_remove_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
