<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='page',
            field=models.URLField(default='linkedin.com'),
        ),
        migrations.DeleteModel(
            name='page',
        ),
    ]
=======
# Generated by Django 5.0.3 on 2024-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='page',
            field=models.URLField(default='linkedin.com'),
        ),
        migrations.DeleteModel(
            name='page',
        ),
    ]
>>>>>>> 49cc1c162d40e4b298df25389748a49b7cebbf23
