# Generated by Django 5.0.3 on 2024-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0007_alter_qrcode_page_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='page',
            field=models.URLField(default=''),
        ),
    ]
