<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0008_qrcode_title_alter_qrcode_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='title',
            field=models.CharField(default='QRcode name', max_length=50),
        ),
    ]
=======
# Generated by Django 5.0.3 on 2024-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0008_qrcode_title_alter_qrcode_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='title',
            field=models.CharField(default='QRcode name', max_length=50),
        ),
    ]
>>>>>>> 49cc1c162d40e4b298df25389748a49b7cebbf23
